### ISSUE TITLE
make plots beautiful

### ISSUE THREAD

**Issue by milanwiedemann** [CDU-data-science-team/phaRmacyForecasting#5]
- labels
- font size
- colours

see some of these resources

**Comment by ChrisBeeley** [comment]
What did we decide about plots? Porting into package, right?

**Comment by milanwiedemann** [comment]
yes, I think we wanted to add it to the nottshc package ... but not sure if we actually made enough progress to have a template

**Comment by ChrisBeeley** [comment]
I was about to make a PR but then I thought {nottshc} is private, so we don't really want to create dependencies on it. I know we keep talking about it but let's discuss packages and themes and stuff in team meeting on Monday
